services: docker
script: >-
  if [ -n "$TRAVIS_TAG" ]; then
    VERSION_ARG="--build-arg SHUFFLEBOT_VERSION=$TRAVIS_TAG+build.$TRAVIS_BUILD_NUMBER.sha-$TRAVIS_COMMIT";
  fi;
  docker build -t shufflebot $VERSION_ARG .
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    on:
      branch: latest
    script:
      - docker tag shufflebot epilanthanomai/shufflebot:latest && docker push epilanthanomai/shufflebot:latest
  - provider: script
    on:
      tags: true
    script:
      - docker tag shufflebot epilanthanomai/shufflebot:$TRAVIS_TAG && docker push epilanthanomai/shufflebot:$TRAVIS_TAG
